spring.application.name=backend-xdpmweb

spring.datasource.url=jdbc:postgresql://dpg-d7g7e2po3t8c73c2h5g0-a.singapore-postgres.render.com:5432/dbweb_a2si?sslmode=require

spring.datasource.username=dbweb_a2si_user
spring.datasource.password=o2slhYsVANLSP3iveeLlzH9T99uf42Mf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true