spring.application.name=backend-xdpmweb

spring.datasource.url=jdbc:postgresql://dpg-d6qaulv5r7bs738dpl8g-a.singapore-postgres.render.com/xdpmweb_db?sslmode=require

spring.datasource.username=xdpmweb_db_user
spring.datasource.password=B9u6TTF1M7MEVgWl1TqGOEpPmZ5WbB0p
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect